---
title: "Spondylo vs Met"
output:
  html_document:
    df_print: paged
  pdf_document: default
---


### Downloading the libraries

```{r message=FALSE, warning=FALSE}
library(randomForest)
library(pROC)
library(caret)
library(kernlab)
library(e1071)
library(readxl)
library(Boruta)
```

### Loading the dataset 
```{r}
features <- read_excel("E:/BMF/bakalarka/ML/features.xlsx", sheet = "ML")
```

```{r}
#looking at our variables in the dataset

labels(features)


# change the quality column to a factor type

features$Disease <- as.factor(features$Disease)
```


### Variable selection using Boruta package
```{r message=FALSE, warning=FALSE}
boruta_output <- Boruta(factor(Disease) ~ ., data=na.omit(features), doTrace=2) 
plot(boruta_output, cex.axis=.7, las=2, xlab="", main="Variable Importance") 

```

```{r}
# listing the confirmed

boruta_signif <- names(boruta_output$finalDecision[boruta_output$finalDecision %in% c("Confirmed")])
print(boruta_signif)
```

```{r}
# having overview of all the decisions

vypis <- attStats(boruta_output)
print(vypis)

```

### TRAIN AND TEST SET 
```{r}
# randomly selecting 70% of the rows in data

index <- sample(1:nrow(features),size = 0.70*nrow(features))

# showing selected rows for our training set

index
```

```{r}
# using selected 70% of the data for training set and the rest of 30% for testing set

train.split <- features[index,]
test.split <- features[-index,]
```

#### Random Forest Model
```{r}
rf <- randomForest(factor(Disease)~GLCM_homogeneity
                   +GLCM_contrast
                   +GLCM_dissimilarity
                   +GLRLM_SRE
                   +GLZLM_GLNU
                   +GLZLM_ZP
                   +NGLDM_Busyness
                   +GLRLM_LGRE
                   +GLRLM_SRLGE
                   +GLZLM_SZHGE
                   +GLRLM_GLNU
                   +GLRLM_RLNU
                   +GLRLM_RP
                   +GLZLM_LZE
                   +GLZLM_HGZE
                   +GLZLM_LZLGE
                   +GLZLM_LZHGE
                   +NGLDM_Coarseness
                   +NGLDM_Contrast
                   +GLZLM_SZE,data=train.split, ntree=400, mtry=4, na.action = na.omit, importance=TRUE)
```

```{r}
# showing the variable importance performing in the random forest model

varImpPlot(rf)
```

```{r message=FALSE, warning=FALSE}
# make predictions on our testing data

rf_pred <- predict(rf, test.split)
print(rf_pred)
```
```{r}
# confusion matrix for the prediction

confusionMatrix(as.factor(rf_pred), as.factor(test.split$Disease))
```

```{r message=FALSE, warning=FALSE}
# ROC curve - how well it predicted

rf_pred <- predict(rf, test.split, type = "prob")
ROC_rf <- roc(factor(test.split$Disease) ,rf_pred[ ,1])
plot(ROC_rf, 
     print.auc=TRUE,
     auc.polygon=TRUE,
     grid=c(0.1, 0.2),
     max.auc.polygon=TRUE,
     print.thres=TRUE,
     auc.polygon.col="skyblue")

#we can save this model 
save(rf , file = 'MyML.rda')
```

#### Logistic regression model

```{r}

# logistic regression model

lr <- glm(factor(Disease)~GLCM_homogeneity
          +GLCM_contrast
          +GLCM_dissimilarity
          +GLRLM_SRE
          +GLZLM_GLNU
          +GLZLM_ZP
          +NGLDM_Busyness
          +GLRLM_LGRE
          +GLRLM_SRLGE
          +GLZLM_SZHGE
          +GLRLM_GLNU
          +GLRLM_RLNU
          +GLRLM_RP
          +GLZLM_LZE
          +GLZLM_LZLGE
          +NGLDM_Coarseness
          +NGLDM_Contrast
          +GLZLM_SZE, data = train.split, family = "binomial", control= list(maxit=150))
print(lr)

```


```{r}

# make predictions for our testing data
lr_pred <- predict(lr, test.split, type = "response")
lr_pred


```


```{r message=FALSE, warning=FALSE}
# ROC curve - how well it predicted
ROC_lr <- roc(factor(test.split$Disease), lr_pred)
plot(ROC_lr, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     max.auc.polygon=TRUE,print.thres=TRUE,auc.polygon.col="skyblue")
```

#### Support vector machines

```{r}
# support vector machine model

svm_traintest <- svm(factor(Disease)~GLCM_homogeneity
                     +GLCM_contrast
                     +GLCM_dissimilarity
                     +GLRLM_SRE
                     +GLZLM_GLNU
                     +GLZLM_ZP
                     +NGLDM_Busyness
                     +GLRLM_LGRE
                     +GLRLM_SRLGE
                     +GLZLM_SZHGE
                     +GLRLM_GLNU
                     +GLRLM_RLNU
                     +GLRLM_RP
                     +GLZLM_LZE
                     +GLZLM_LZLGE
                     +NGLDM_Coarseness
                     +NGLDM_Contrast
                     +GLZLM_SZE,data=train.split)

```

```{r}
# making predictions on our testing data
svm_traintest_pred <- predict(svm_traintest, test.split, type = "prob")

```

```{r message=FALSE, warning=FALSE}
# ROC curve - how well it predicted

ROC_svm1 <- roc(factor(test.split$Disease), as.ordered(svm_traintest_pred))
plot(ROC_svm1,print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     max.auc.polygon=TRUE,print.thres=TRUE,auc.polygon.col="skyblue")
```


```{r message=FALSE, warning=FALSE}
# making comparison of all three methods 

roc.rf1 <- plot.roc(factor(test.split$Disease), rf_pred[ ,2], main="Statistical comparison of method: Train/Test split", col="1", percent=TRUE,grid=c(0.1, 0.2))
roc.lr1 <- lines.roc(factor(test.split$Disease), lr_pred, col="2", percent=TRUE)
roc.svm1 <- lines.roc(factor(test.split$Disease), as.ordered(svm_traintest_pred), col="4", percent=TRUE)

legend("bottomright", legend=c("Random Forest, AUC=94.44%", "Logistic Regression, AUC=66.67%", "Support Vector Machines, AUC=83.33%"), col=c("1", "2", "4"), lwd=2)
```

#### Validation of the best model - random forest model

```{r}
# uploading our validation set 

validacia <- read_excel("validacia.xlsx")

```
```{r}
# making predictions 

valid <- predict(rf, validacia, type = "prob")

```


```{r message=FALSE, warning=FALSE}
# plotting ROC curve 

ROC_rf_valid <- roc(factor(validacia$Disease) ,valid[ ,2])

plot(ROC_rf_valid, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     max.auc.polygon=TRUE,print.thres=TRUE,
     auc.polygon.col="skyblue")

# we can show confidence intervals with: ci.auc(ROC_rf_valid)

```







